version : '3'
services:
  react-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /reactproject/p1/node_modules
      - .:/reactproject/p1
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /reactproject/p1/node_modules
      - .:/reactproject/p1
    command: ["npm","run","test"]
      